language: python
python:
    - 3.5
before_install:
    - sudo apt-get install python-qt4
install:
    - pip install sip numpy pandas matplotlib scipy guidata
script: python ./src/refcurv.py
  


    

